### PR TITLE
updates text in changes file and pr template

### PR DESCRIPTION
**Pull request by kjaymiller**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Do tests and lints pass with this change?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [X] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

Resolves https://github.com/valkey-io/valkey-py/issues/31 by removing the changes update request in the PR template and adding a comment to the top of the CHANGES file.

This is a cleaned up version of #33

### CODE REVIEW

**Comment by kjaymiller** [comment]
@ahmedsobeh - it was easier to submit a new PR from a different branch.

**Review by aiven-sal — APPROVED** [review]
Thanks!

**Review by aiven-sal — APPROVED** [review]

**Review by ahmedsobeh — APPROVED** [review]

**Comment by ahmedsobeh** [comment]
LGTM! Thanks for submitting it again

**Review by aaron-muti-420 — COMMENTED** [review]
I'm New here.., How do I Perform a Review on this PR?

**Comment by mkmkme** [comment]
@aaron-muti-420 you can click on a line you want to add a comment to in the tab called "Files changes". While writing a comment, there will be either "Start a review" and "Add a single comment" buttons. Use whatever feels more natural.

**Pull request merged**
