### PR TITLE
Replace hiredis dependency with libvalkey

### PR DESCRIPTION
**Pull request by mkmkme**
**NOTE:** This PR should not be merged until `libvalkey-py` is moved into `valkey-io` and the first version of `libvalkey-py` is released to PyPI!

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Do tests and lints pass with this change?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [X] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [ ] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

This changeset changes hiredis dependency with libvalkey.

### CODE REVIEW

**Comment by mkmkme** [comment]
converted to draft until PyPI package for libvalkey-py is published

**Comment by kjaymiller** [comment]
@mkmkme - I see that both of the constraints you mentioned should be completed now (libvalkey and libvalkey-py are in the valkey org and libvalkey-py has been published to pypi)

**Comment by mkmkme** [comment]
@kjaymiller I still haven't enabled the breaking changes yet, they are behind the flag in `libvalkey.Reader`. When I turn them on, the RESP3 tests start failing. Now I need to fix them, and then this is good to go :)

**Comment by mkmkme** [comment]
@kjaymiller JFYI the release I've done was not good enough. I have to release a new one.

**Comment by mkmkme** [comment]
The tests are failing. I know the reason and investigating it

**Comment by mkmkme** [comment]
@aiven-sal @ahmedsobeh all tests are green and `invoke cluster-tests -c --protocol=3 --uvloop` run locally passed as well.

Shall we remove the RESP3 libvalkey cluster exclusion as per https://github.com/valkey-io/valkey-py/pull/55/files or will we do this separately?

**Comment by ahmedsobeh** [comment]
> @aiven-sal @ahmedsobeh all tests are green and `invoke cluster-tests -c --protocol=3 --uvloop` run locally passed as well.
> 
> Shall we remove the RESP3 libvalkey cluster exclusion as per https://github.com/valkey-io/valkey-py/pull/55/files or will we do this separately?

There is already a PR for it: https://github.com/valkey-io/valkey-py/pull/55

**Review by aiven-sal — APPROVED** [review]
Thank you!

**Pull request merged**
